name: Run jamesgeorge007/github-activity-readme

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  github-activity-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'On a roll... 🚀🚀🚀'
          MAX_LINES: 10
